import type { Product } from "./types";
import { KSP_AFFILIATE_ID } from "./config";
import { GENERATED_PRODUCTS } from "./generated-products";

// Affiliate link helpers - all use SEARCH URLs to avoid 404s on hardcoded SKUs
function kspSearch(query: string): string {
  // KSP affiliate entry URL - sets cookie, then user can browse
  return `https://ksp.co.il/m_action/api/search?text=${encodeURIComponent(query)}&aff=${KSP_AFFILIATE_ID}`;
}
function amazonSearch(query: string): string {
  // Filter to Amazon Global Store (ships internationally including Israel)
  return `https://www.amazon.com/s?k=${encodeURIComponent(query)}&i=amazon-global-store&tag=hashveli-20`;
}
function aliSearch(query: string): string {
  // Direct AliExpress search - tracking via cookie when user clicks our affiliate
  return `https://www.aliexpress.com/wholesale?SearchText=${encodeURIComponent(query)}`;
}
function sheinSearch(query: string): string {
  return `https://us.shein.com/pdsearch/${encodeURIComponent(query)}/`;
}

const kspLink = (productName: string, _sku?: string) => kspSearch(productName);
const aliLink = (_id: string, productName?: string) =>
  aliSearch(productName || _id);
const amazonLink = (_asin: string, productName?: string) =>
  amazonSearch(productName || _asin);
const sheinLink = (_id: string, productName?: string) =>
  sheinSearch(productName || _id);

const now = "2026-06-07T00:00:00Z";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "apple-airpods-pro-2",
    slug: "apple-airpods-pro-2",
    title: "אוזניות Apple AirPods Pro 2",
    titleEn: "Apple AirPods Pro 2",
    description:
      "אוזניות אלחוטיות עם ביטול רעשים אקטיבי, מצב שקיפות, אודיו מרחבי וקייס טעינה אלחוטי MagSafe.",
    category: "headphones",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f37?w=800&q=80",
    specs: {
      "ביטול רעשים": "אקטיבי (ANC)",
      "חיי סוללה": "עד 6 שעות",
      "טעינה אלחוטית": "כן (MagSafe)",
      "Bluetooth": "5.3",
      "עמידות במים": "IPX4",
    },
    offers: [
      {
        vendor: "ksp",
        price: 899,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("AIRPODSPRO2"),
        vendorSku: "AIRPODSPRO2",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 750,
        shippingPrice: 80,
        inStock: true,
        url: amazonLink("B0BDHWDR12"),
        vendorSku: "B0BDHWDR12",
        lastUpdated: now,
      },
      {
        vendor: "aliexpress",
        price: 620,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("airpods123"),
        lastUpdated: now,
      },
    ],
    rating: 4.7,
    reviewCount: 12453,
    createdAt: now,
  },
  {
    id: "samsung-galaxy-s24-ultra",
    slug: "samsung-galaxy-s24-ultra",
    title: "Samsung Galaxy S24 Ultra 256GB",
    description: "סמארטפון דגל של סמסונג עם מסך 6.8 אינץ', צילום 200MP, עט S-Pen מובנה ומעבד Snapdragon 8 Gen 3.",
    category: "smartphones",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80",
    specs: {
      "מסך": "6.8 אינץ' QHD+",
      "מצלמה": "200MP + 50MP + 12MP + 10MP",
      "מעבד": "Snapdragon 8 Gen 3",
      "אחסון": "256GB",
      "סוללה": "5000mAh",
    },
    offers: [
      {
        vendor: "ksp",
        price: 4290,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("S24ULTRA256"),
        vendorSku: "S24ULTRA256",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 3800,
        shippingPrice: 150,
        inStock: true,
        url: amazonLink("B0CMDRCZBJ"),
        vendorSku: "B0CMDRCZBJ",
        lastUpdated: now,
      },
      {
        vendor: "aliexpress",
        price: 3450,
        shippingPrice: 0,
        inStock: false,
        url: aliLink("s24ultra"),
        lastUpdated: now,
      },
    ],
    rating: 4.6,
    reviewCount: 8721,
    createdAt: now,
  },
  {
    id: "macbook-air-m3",
    slug: "macbook-air-m3-13",
    title: 'MacBook Air 13" M3 256GB',
    description: "מחשב נייד אולטרה דק עם שבב M3 חדשני, 8GB RAM, מסך Liquid Retina 13.6 אינץ' ועד 18 שעות סוללה.",
    category: "laptops",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
    specs: {
      "שבב": "Apple M3 8-core",
      "מסך": "13.6 אינץ' Liquid Retina",
      "זיכרון": "8GB",
      "אחסון": "256GB SSD",
      "סוללה": "עד 18 שעות",
    },
    offers: [
      {
        vendor: "ksp",
        price: 4990,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("MBAIR13M3"),
        vendorSku: "MBAIR13M3",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 4200,
        shippingPrice: 220,
        inStock: true,
        url: amazonLink("B0CX23V2ZK"),
        vendorSku: "B0CX23V2ZK",
        lastUpdated: now,
      },
    ],
    rating: 4.8,
    reviewCount: 5482,
    createdAt: now,
  },
  {
    id: "iphone-15-pro",
    slug: "apple-iphone-15-pro-128",
    title: "Apple iPhone 15 Pro 128GB",
    description: "אייפון 15 פרו עם שבב A17 Pro, מצלמה ראשית 48MP, גוף טיטניום ושיפורים בצילום וידאו ProRes.",
    category: "smartphones",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1696446702183-be7f55ee4f76?w=800&q=80",
    specs: {
      "מסך": "6.1 אינץ' Super Retina XDR",
      "מצלמה": "48MP + 12MP + 12MP",
      "מעבד": "A17 Pro",
      "אחסון": "128GB",
      "חיבור": "USB-C",
    },
    offers: [
      {
        vendor: "ksp",
        price: 4290,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("IPH15PRO128"),
        vendorSku: "IPH15PRO128",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 3950,
        shippingPrice: 120,
        inStock: true,
        url: amazonLink("B0CHX1W1XY"),
        vendorSku: "B0CHX1W1XY",
        lastUpdated: now,
      },
    ],
    rating: 4.7,
    reviewCount: 9842,
    createdAt: now,
  },
  {
    id: "sony-wh1000xm5",
    slug: "sony-wh-1000xm5",
    title: "אוזניות Sony WH-1000XM5",
    description: "אוזניות אלחוטיות עוטפות אוזן עם ביטול הרעשים הטוב בעולם, איכות שמע יוצאת דופן ו-30 שעות סוללה.",
    category: "headphones",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
    specs: {
      "ביטול רעשים": "אקטיבי (ANC) מתקדם",
      "חיי סוללה": "עד 30 שעות",
      "טעינה מהירה": "3 דק' = 3 שעות",
      "משקל": "250 גרם",
      "Bluetooth": "5.2",
    },
    offers: [
      {
        vendor: "ksp",
        price: 1490,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("SONYXM5"),
        vendorSku: "SONYXM5",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 1180,
        shippingPrice: 100,
        inStock: true,
        url: amazonLink("B09XS7JWHH"),
        vendorSku: "B09XS7JWHH",
        lastUpdated: now,
      },
      {
        vendor: "aliexpress",
        price: 990,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("sonyxm5"),
        lastUpdated: now,
      },
    ],
    rating: 4.8,
    reviewCount: 23445,
    createdAt: now,
  },
  {
    id: "apple-watch-s9",
    slug: "apple-watch-series-9-45mm",
    title: "Apple Watch Series 9 45mm",
    description: "שעון חכם מתקדם עם מסך גדול ובהיר, מחוות Double Tap, וצ'יפ S9 מהיר במיוחד.",
    category: "smartwatches",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80",
    specs: {
      "גודל": "45mm",
      "מסך": "Always-On Retina",
      "צ'יפ": "S9 SiP",
      "חיי סוללה": "18 שעות",
      "עמידות במים": "50 מטר",
    },
    offers: [
      {
        vendor: "ksp",
        price: 1790,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("AW9-45"),
        vendorSku: "AW9-45",
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 1550,
        shippingPrice: 120,
        inStock: true,
        url: amazonLink("B0CHX3QBCH"),
        vendorSku: "B0CHX3QBCH",
        lastUpdated: now,
      },
    ],
    rating: 4.6,
    reviewCount: 4321,
    createdAt: now,
  },
  {
    id: "midi-floral-dress",
    slug: "midi-floral-dress-summer",
    title: "שמלת מידי פרחונית קיצית בוהו",
    description: "שמלת קיץ אווירית עם הדפס פרחים, גזרה רחבה ונוחה, שרוול קצר נפוח. מושלמת לאירועים ולחופשה.",
    category: "fashion",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80",
    specs: {
      "מידות": "S, M, L, XL",
      "חומר": "100% פוליאסטר",
      "אורך": "מידי (עד הברך)",
      "סגנון": "בוהו",
      "סוג כביסה": "במכונה במים קרים",
    },
    offers: [
      {
        vendor: "shein",
        price: 79,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("dress-floral-001"),
        lastUpdated: now,
      },
      {
        vendor: "aliexpress",
        price: 65,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("floraldress"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 145,
        shippingPrice: 40,
        inStock: true,
        url: amazonLink("B0CTYZ2BCD"),
        lastUpdated: now,
      },
    ],
    rating: 4.5,
    reviewCount: 8432,
    createdAt: now,
  },
  {
    id: "silver-stud-earrings",
    slug: "silver-cz-stud-earrings",
    title: "עגילי כפתור כסף 925 עם זרקונים",
    description: "עגילי כפתור עדינים מכסף סטרלינג 925 עם אבני זרקון מנצנצות. מתאים לכל יום וגם לאירועים.",
    category: "jewelry",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1635767582909-345d3cca5e22?w=800&q=80",
    specs: {
      "חומר": "כסף 925",
      "אבן": "זרקון CZ",
      "גודל": "6mm",
      "סגירה": "פין דחיפה",
      "כיסוי": "אנטי-אלרגי",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 28,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("cz-studs"),
        lastUpdated: now,
      },
      {
        vendor: "shein",
        price: 45,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("earrings-002"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 89,
        shippingPrice: 35,
        inStock: true,
        url: amazonLink("B0BLXR4CDE"),
        lastUpdated: now,
      },
    ],
    rating: 4.6,
    reviewCount: 15672,
    createdAt: now,
  },
  {
    id: "leather-tote-bag",
    slug: "vegan-leather-tote-bag",
    title: "תיק טוט עור צמחוני גדול",
    description: "תיק טוט מעוצב מעור צמחוני איכותי, מכיל לפטופ עד 15.6 אינץ', עם ידיות מחוזקות וכיס פנימי עם רוכסן.",
    category: "accessories",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800&q=80",
    specs: {
      "מידות": "40x35x12 ס\"מ",
      "חומר": "PU עור צמחוני",
      "מתאים ללפטופ": "עד 15.6 אינץ'",
      "כיסים פנימיים": "2 + רוכסן",
      "צבעים": "שחור, חום, ניוד, חרדל",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 89,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("tote-bag"),
        lastUpdated: now,
      },
      {
        vendor: "shein",
        price: 125,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("bag-003"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 245,
        shippingPrice: 50,
        inStock: true,
        url: amazonLink("B0CGHMJ7KL"),
        lastUpdated: now,
      },
    ],
    rating: 4.4,
    reviewCount: 5421,
    createdAt: now,
  },
  {
    id: "matte-liquid-lipstick-set",
    slug: "matte-liquid-lipstick-12pcs",
    title: "סט שפתונים נוזליים מאט - 12 גוונים",
    description: "סט של 12 שפתונים נוזליים מאט עמידים לאורך כל היום. כל הגוונים שאת צריכה - מנוד עד אדום עז.",
    category: "beauty",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1599733589046-9a8e21f5e2f9?w=800&q=80",
    specs: {
      "כמות": "12 יחידות",
      "סוג": "נוזלי מאט",
      "עמידות": "עד 12 שעות",
      "נפח": "3.5 מ\"ל ליחידה",
      "טבעוני": "כן",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 39,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("lipstick12"),
        lastUpdated: now,
      },
      {
        vendor: "shein",
        price: 69,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("lipstick-004"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 129,
        shippingPrice: 30,
        inStock: true,
        url: amazonLink("B0BQXR7KMN"),
        lastUpdated: now,
      },
    ],
    rating: 4.3,
    reviewCount: 9876,
    createdAt: now,
  },
  {
    id: "led-vanity-mirror",
    slug: "led-makeup-vanity-mirror",
    title: "מראת איפור עם תאורת LED מתכווננת",
    description: "מראת איפור הוליוודית עם 12 נורות LED, 3 רמות תאורה, מסך מגע לכוונון, ומעמד מסתובב 360°.",
    category: "beauty",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1522335789203-aaa1f4f47cb6?w=800&q=80",
    specs: {
      "מספר נורות": "12 LED",
      "רמות תאורה": "3",
      "סיבוב": "360°",
      "טעינה": "USB",
      "מסך": "מגע",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 79,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("ledmirror"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 159,
        shippingPrice: 45,
        inStock: true,
        url: amazonLink("B0BWXY8PQR"),
        lastUpdated: now,
      },
      {
        vendor: "ksp",
        price: 199,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("LEDMIRROR12"),
        vendorSku: "LEDMIRROR12",
        lastUpdated: now,
      },
    ],
    rating: 4.7,
    reviewCount: 12345,
    createdAt: now,
  },
  {
    id: "hair-curling-iron-auto",
    slug: "automatic-hair-curler-wand",
    title: "מכשיר תלתלים אוטומטי 32mm",
    description: "מכשיר תלתלים מקצועי אוטומטי - מסובב את השיער לבד! 6 רמות חום, ציפוי קרמי, מתאים לכל סוגי השיער.",
    category: "haircare",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    specs: {
      "קוטר": "32mm",
      "רמות חום": "6 (130-230°C)",
      "ציפוי": "קרמי + טורמלין",
      "זמן חימום": "30 שניות",
      "ביטול אוטומטי": "כן, אחרי שעה",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 95,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("curler32"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 189,
        shippingPrice: 50,
        inStock: true,
        url: amazonLink("B0CKLMN567"),
        lastUpdated: now,
      },
      {
        vendor: "ksp",
        price: 249,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("CURL32AUTO"),
        vendorSku: "CURL32AUTO",
        lastUpdated: now,
      },
    ],
    rating: 4.5,
    reviewCount: 6789,
    createdAt: now,
  },
  {
    id: "phone-case-magsafe-iphone15",
    slug: "iphone-15-magsafe-clear-case",
    title: "כיסוי שקוף MagSafe לאייפון 15",
    description: "כיסוי שקוף קריסטל עם תמיכה ב-MagSafe, גומי TPU רך נגד נפילות, ולא מצהיב עם הזמן.",
    category: "phone-accessories",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80",
    specs: {
      "דגם": "iPhone 15 / 15 Pro / 15 Pro Max",
      "תמיכה ב-MagSafe": "כן",
      "חומר": "TPU + PC",
      "הגנה": "MIL-STD 810G",
      "לא מצהיב": "כן",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 25,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("case-magsafe"),
        lastUpdated: now,
      },
      {
        vendor: "shein",
        price: 35,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("case-005"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 79,
        shippingPrice: 25,
        inStock: true,
        url: amazonLink("B0CHX7KMNP"),
        lastUpdated: now,
      },
      {
        vendor: "ksp",
        price: 149,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("CASE-IP15"),
        vendorSku: "CASE-IP15",
        lastUpdated: now,
      },
    ],
    rating: 4.4,
    reviewCount: 18234,
    createdAt: now,
  },
  {
    id: "kids-magnetic-blocks-100",
    slug: "magnetic-building-blocks-kids",
    title: "ערכת קוביות מגנט לילדים - 100 חלקים",
    description: "ערכת בנייה חינוכית עם 100 קוביות מגנט צבעוניות. מפתח יצירתיות, מוטוריקה ועוזר בלמידת צורות וצבעים.",
    category: "kids",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1558877385-81a1c7e67d72?w=800&q=80",
    specs: {
      "מספר חלקים": "100",
      "גיל מומלץ": "3+",
      "חומר": "ABS פלסטיק בטוח",
      "תקני בטיחות": "CE, EN71",
      "כולל": "ספר הוראות + תיק נשיאה",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 89,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("magblocks"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 159,
        shippingPrice: 40,
        inStock: true,
        url: amazonLink("B0BXPQ5KLM"),
        lastUpdated: now,
      },
      {
        vendor: "ksp",
        price: 299,
        shippingPrice: 0,
        inStock: true,
        url: kspLink("MAG100KIDS"),
        vendorSku: "MAG100KIDS",
        lastUpdated: now,
      },
    ],
    rating: 4.8,
    reviewCount: 9123,
    createdAt: now,
  },
  {
    id: "memory-foam-slippers",
    slug: "memory-foam-house-slippers",
    title: "נעלי בית מבד נעים עם ספוג זיכרון",
    description: "נעלי בית מפנקות עם סוליית ספוג זיכרון, בטנה רכה, וסוליית גומי נגד החלקה. נוחות מקסימלית לבית.",
    category: "fashion",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1582897085656-c636d006a246?w=800&q=80",
    specs: {
      "מידות": "36-42",
      "סוליה": "ספוג זיכרון",
      "בטנה": "פרווה סינתטית",
      "סוליה חיצונית": "גומי נגד החלקה",
      "כביסה": "במכונה",
    },
    offers: [
      {
        vendor: "aliexpress",
        price: 45,
        shippingPrice: 0,
        inStock: true,
        url: aliLink("slippers"),
        lastUpdated: now,
      },
      {
        vendor: "shein",
        price: 65,
        shippingPrice: 25,
        inStock: true,
        url: sheinLink("slippers-006"),
        lastUpdated: now,
      },
      {
        vendor: "amazon",
        price: 119,
        shippingPrice: 30,
        inStock: true,
        url: amazonLink("B0BCDFG456"),
        lastUpdated: now,
      },
    ],
    rating: 4.6,
    reviewCount: 7234,
    createdAt: now,
  },
  {
    id: "lingerie-lace-set",
    slug: "lace-bra-panty-set",
    title: "סט תחתון וחזייה תחרה רומנטי",
    description: "סט הלבשה תחתונה אלגנטי מתחרה איכותית. חזייה עם רפידות נוחות וגזרה מחמיאה. זמין במגוון צבעים ומידות.",
    category: "lingerie",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1606744824163-985d376605aa?w=800&q=80",
    specs: { "מידות": "32A-40D", "חומר": "תחרה + ספנדקס", "כביסה": "ביד", "כולל": "חזייה + תחתון", "צבעים": "שחור, לבן, אדום, ניוד" },
    offers: [
      { vendor: "shein", price: 49, shippingPrice: 25, inStock: true, url: sheinLink("lingerie-001"), lastUpdated: now },
      { vendor: "aliexpress", price: 35, shippingPrice: 0, inStock: true, url: aliLink("lingerie"), lastUpdated: now },
      { vendor: "amazon", price: 119, shippingPrice: 30, inStock: true, url: amazonLink("B0CABC1234"), lastUpdated: now },
    ],
    rating: 4.3, reviewCount: 4521, createdAt: now,
  },
  {
    id: "white-sneakers-women",
    slug: "white-leather-sneakers-women",
    title: "נעלי סניקרס לבנות עור לנשים",
    description: "סניקרס קלאסיות מעור צמחוני, סוליה רכה לנוחות מרבית, מתאימות לכל לוק יומיומי או ספורטיבי.",
    category: "shoes",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    specs: { "מידות": "35-42", "חומר עליון": "PU עור", "סוליה": "גומי", "גובה עקב": "2 ס\"מ", "סגנון": "Low-top" },
    offers: [
      { vendor: "aliexpress", price: 75, shippingPrice: 0, inStock: true, url: aliLink("sneakers"), lastUpdated: now },
      { vendor: "shein", price: 115, shippingPrice: 25, inStock: true, url: sheinLink("shoes-002"), lastUpdated: now },
      { vendor: "amazon", price: 245, shippingPrice: 45, inStock: true, url: amazonLink("B0DEF56789"), lastUpdated: now },
    ],
    rating: 4.4, reviewCount: 11234, createdAt: now,
  },
  {
    id: "mens-polo-shirts-3pack",
    slug: "mens-classic-polo-shirt-3pack",
    title: "סט 3 חולצות פולו לגברים",
    description: "סט של 3 חולצות פולו קלאסיות בכותנה איכותית. גזרה רגילה, כפתורים אופנתיים, מתאים לעבודה ולבילוי.",
    category: "men-fashion",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&q=80",
    specs: { "מידות": "S-XXL", "חומר": "100% כותנה", "כמות": "3 יחידות", "גזרה": "Regular Fit", "כביסה": "במכונה" },
    offers: [
      { vendor: "aliexpress", price: 95, shippingPrice: 0, inStock: true, url: aliLink("polos"), lastUpdated: now },
      { vendor: "shein", price: 139, shippingPrice: 25, inStock: true, url: sheinLink("polo-003"), lastUpdated: now },
      { vendor: "amazon", price: 195, shippingPrice: 40, inStock: true, url: amazonLink("B0GHI78901"), lastUpdated: now },
    ],
    rating: 4.5, reviewCount: 8923, createdAt: now,
  },
  {
    id: "perfume-floral-edp",
    slug: "floral-eau-de-parfum-100ml",
    title: "בושם פרחוני יוקרתי לנשים EDP 100ml",
    description: "בושם פרחוני אלגנטי עם נוטות של יסמין, ורד ופציולי. עמיד עד 8 שעות. בקבוק מעוצב מתאים גם למתנה.",
    category: "perfume",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    specs: { "נפח": "100ml", "סוג": "Eau de Parfum", "עמידות": "6-8 שעות", "משפחה": "פרחוני", "מתאים ל": "ערב ויום" },
    offers: [
      { vendor: "aliexpress", price: 85, shippingPrice: 0, inStock: true, url: aliLink("perfume"), lastUpdated: now },
      { vendor: "amazon", price: 189, shippingPrice: 50, inStock: true, url: amazonLink("B0JKL11223"), lastUpdated: now },
      { vendor: "ksp", price: 249, shippingPrice: 0, inStock: true, url: kspLink("PERFUME100"), vendorSku: "PERFUME100", lastUpdated: now },
    ],
    rating: 4.4, reviewCount: 6234, createdAt: now,
  },
  {
    id: "vitamin-c-serum",
    slug: "vitamin-c-brightening-serum",
    title: "סרום ויטמין C להבהרה והזנת העור",
    description: "סרום פנים פעיל עם 20% ויטמין C, חומצה היאלורונית וויטמין E. מפחית כתמים, מוסיף זוהר ומונע סימני זקנה.",
    category: "skincare",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    specs: { "נפח": "30ml", "פעיל": "Vitamin C 20%", "מתאים ל": "כל סוגי העור", "טבעוני": "כן", "פתוח אחרי": "12 חודשים" },
    offers: [
      { vendor: "aliexpress", price: 45, shippingPrice: 0, inStock: true, url: aliLink("vitc"), lastUpdated: now },
      { vendor: "shein", price: 79, shippingPrice: 25, inStock: true, url: sheinLink("serum-004"), lastUpdated: now },
      { vendor: "amazon", price: 149, shippingPrice: 30, inStock: true, url: amazonLink("B0MNO45678"), lastUpdated: now },
    ],
    rating: 4.6, reviewCount: 14567, createdAt: now,
  },
  {
    id: "cat-eye-sunglasses",
    slug: "cat-eye-uv400-sunglasses",
    title: "משקפי שמש Cat Eye עם הגנת UV400",
    description: "משקפי שמש בסגנון Cat Eye רטרו, מסגרת מאצטט איכותי, עדשות פולריות עם הגנה מלאה מקרני UV.",
    category: "sunglasses",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
    specs: { "סוג עדשה": "פולריות UV400", "מסגרת": "אצטט", "סגנון": "Cat Eye", "כולל": "נרתיק + מטלית", "צבעים": "שחור, לבן, ורוד" },
    offers: [
      { vendor: "aliexpress", price: 55, shippingPrice: 0, inStock: true, url: aliLink("cateye"), lastUpdated: now },
      { vendor: "shein", price: 89, shippingPrice: 25, inStock: true, url: sheinLink("sunglass-005"), lastUpdated: now },
      { vendor: "amazon", price: 159, shippingPrice: 35, inStock: true, url: amazonLink("B0PQR91011"), lastUpdated: now },
    ],
    rating: 4.5, reviewCount: 7890, createdAt: now,
  },
  {
    id: "minimalist-watch-women",
    slug: "minimalist-mesh-watch-women",
    title: "שעון יד מינימליסטי לנשים עם רצועת רשת",
    description: "שעון יד אלגנטי בסגנון מינימליסטי, מסגרת זהב ורוד, רצועת רשת נירוסטה. מתאים לכל אירוע.",
    category: "watches",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80",
    specs: { "תנועה": "קוורץ יפני", "מסגרת": "נירוסטה", "רצועה": "Mesh נירוסטה", "עמיד למים": "3ATM", "קוטר": "36mm" },
    offers: [
      { vendor: "aliexpress", price: 89, shippingPrice: 0, inStock: true, url: aliLink("watch-min"), lastUpdated: now },
      { vendor: "amazon", price: 195, shippingPrice: 40, inStock: true, url: amazonLink("B0STU13141"), lastUpdated: now },
      { vendor: "ksp", price: 299, shippingPrice: 0, inStock: true, url: kspLink("WATCH-MIN"), vendorSku: "WATCH-MIN", lastUpdated: now },
    ],
    rating: 4.6, reviewCount: 5678, createdAt: now,
  },
  {
    id: "air-fryer-5l",
    slug: "digital-air-fryer-5l",
    title: "סיר טיגון אוויר דיגיטלי 5 ליטר",
    description: "סיר טיגון אוויר חכם עם מסך LCD, 8 תכניות מוכנות, טכנולוגיית 360° לבישול אחיד וללא שמן. בריא וטעים.",
    category: "kitchen",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1648505126325-c8e1b0f6c8c7?w=800&q=80",
    specs: { "נפח": "5 ליטר", "הספק": "1700W", "תכניות": "8", "מסך": "LCD מגע", "טמפ' מקס": "200°C" },
    offers: [
      { vendor: "aliexpress", price: 295, shippingPrice: 0, inStock: true, url: aliLink("airfryer"), lastUpdated: now },
      { vendor: "amazon", price: 449, shippingPrice: 60, inStock: true, url: amazonLink("B0VWX15161"), lastUpdated: now },
      { vendor: "ksp", price: 599, shippingPrice: 0, inStock: true, url: kspLink("AIRFRY5L"), vendorSku: "AIRFRY5L", lastUpdated: now },
    ],
    rating: 4.7, reviewCount: 23456, createdAt: now,
  },
  {
    id: "bamboo-sheets-set",
    slug: "bamboo-cooling-sheets-queen",
    title: "סט מצעים מבמבוק קוויין - 4 חלקים",
    description: "סט מצעי במבוק יוקרתי עם טכנולוגיית קירור. נושמים, רכים מאוד וידידותיים לעור. כולל: סדין, ציפת מזרן, 2 ציפיות.",
    category: "bedding",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    specs: { "מידה": "Queen (160x200)", "חומר": "100% במבוק", "צפיפות חוטים": "300TC", "כולל": "4 חלקים", "צבעים": "לבן, אפור, ניוד, ורוד" },
    offers: [
      { vendor: "aliexpress", price: 159, shippingPrice: 0, inStock: true, url: aliLink("bamboosheets"), lastUpdated: now },
      { vendor: "shein", price: 219, shippingPrice: 25, inStock: true, url: sheinLink("sheets-006"), lastUpdated: now },
      { vendor: "amazon", price: 349, shippingPrice: 70, inStock: true, url: amazonLink("B0YZA17181"), lastUpdated: now },
      { vendor: "ksp", price: 499, shippingPrice: 0, inStock: true, url: kspLink("BAMBOOQ"), vendorSku: "BAMBOOQ", lastUpdated: now },
    ],
    rating: 4.7, reviewCount: 9876, createdAt: now,
  },
  {
    id: "baby-monitor-wifi",
    slug: "wifi-baby-monitor-1080p",
    title: "בייבי מוניטור WiFi עם מצלמת 1080p",
    description: "מצלמת מעקב לתינוק עם רזולוציית Full HD, ראיית לילה, חיישן תנועה ובכי, אפליקציה לסמארטפון.",
    category: "baby",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1607734834519-d8576ae60ea4?w=800&q=80",
    specs: { "רזולוציה": "1080p Full HD", "ראיית לילה": "כן, אינפרא", "חיישנים": "תנועה + קול", "אפליקציה": "iOS + Android", "סיבוב": "Pan 355°/Tilt 110°" },
    offers: [
      { vendor: "aliexpress", price: 145, shippingPrice: 0, inStock: true, url: aliLink("baby-cam"), lastUpdated: now },
      { vendor: "amazon", price: 289, shippingPrice: 50, inStock: true, url: amazonLink("B0BCD19202"), lastUpdated: now },
      { vendor: "ksp", price: 449, shippingPrice: 0, inStock: true, url: kspLink("BABYCAM"), vendorSku: "BABYCAM", lastUpdated: now },
    ],
    rating: 4.5, reviewCount: 6543, createdAt: now,
  },
  {
    id: "yoga-mat-tpe",
    slug: "tpe-eco-yoga-mat-6mm",
    title: "מזרן יוגה אקולוגי TPE 6mm עם נשיאה",
    description: "מזרן יוגה כפול-שכבה מ-TPE ידידותי לסביבה, ללא רעלים, נון-סליפ, עבה ונוח. כולל רצועת נשיאה.",
    category: "sports",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80",
    specs: { "מידות": "183x61 ס\"מ", "עובי": "6mm", "חומר": "TPE אקולוגי", "משקל": "1.2 ק\"ג", "כולל": "רצועת נשיאה" },
    offers: [
      { vendor: "aliexpress", price: 65, shippingPrice: 0, inStock: true, url: aliLink("yogamat"), lastUpdated: now },
      { vendor: "amazon", price: 129, shippingPrice: 40, inStock: true, url: amazonLink("B0CDE21222"), lastUpdated: now },
      { vendor: "ksp", price: 199, shippingPrice: 0, inStock: true, url: kspLink("YOGAMAT6"), vendorSku: "YOGAMAT6", lastUpdated: now },
    ],
    rating: 4.6, reviewCount: 8234, createdAt: now,
  },
  {
    id: "dog-bed-orthopedic",
    slug: "orthopedic-memory-foam-dog-bed",
    title: "מיטת ספוג זיכרון אורתופדית לכלבים",
    description: "מיטת כלב מפנקת עם ספוג זיכרון תומך, כיסוי קטיפה רחיץ במכונה, מתאימה לכלבים בכל גיל.",
    category: "pets",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80",
    specs: { "מידות": "L (90x70)", "מילוי": "ספוג זיכרון", "כיסוי": "קטיפה רחיץ", "מתאים ל": "כלבים בינוניים-גדולים", "צבעים": "אפור, חום, בז'" },
    offers: [
      { vendor: "aliexpress", price: 149, shippingPrice: 0, inStock: true, url: aliLink("dogbed"), lastUpdated: now },
      { vendor: "amazon", price: 279, shippingPrice: 50, inStock: true, url: amazonLink("B0FGH23242"), lastUpdated: now },
      { vendor: "ksp", price: 399, shippingPrice: 0, inStock: true, url: kspLink("DOGBED-L"), vendorSku: "DOGBED-L", lastUpdated: now },
    ],
    rating: 4.7, reviewCount: 4321, createdAt: now,
  },
  {
    id: "car-phone-holder-magnetic",
    slug: "magnetic-car-phone-holder-vent",
    title: "מחזיק טלפון מגנטי לרכב",
    description: "מחזיק מגנטי חזק במיוחד לרכב, מותקן על מאוורר האוויר, סיבוב 360°, מתאים לכל סוגי הטלפונים.",
    category: "car",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=800&q=80",
    specs: { "התקנה": "מאוורר אוויר", "סיבוב": "360°", "מגנטים": "6 מגנטים חזקים", "כולל": "2 פלטות מתכת", "מתאים ל": "טלפונים עד 6.7\"" },
    offers: [
      { vendor: "aliexpress", price: 22, shippingPrice: 0, inStock: true, url: aliLink("car-holder"), lastUpdated: now },
      { vendor: "shein", price: 39, shippingPrice: 25, inStock: true, url: sheinLink("car-007"), lastUpdated: now },
      { vendor: "amazon", price: 69, shippingPrice: 25, inStock: true, url: amazonLink("B0IJK25262"), lastUpdated: now },
      { vendor: "ksp", price: 99, shippingPrice: 0, inStock: true, url: kspLink("CARHOLDER"), vendorSku: "CARHOLDER", lastUpdated: now },
    ],
    rating: 4.3, reviewCount: 19234, createdAt: now,
  },
  {
    id: "smart-bulb-rgb",
    slug: "wifi-smart-bulb-rgb-e27",
    title: "נורת LED חכמה WiFi RGB E27",
    description: "נורה חכמה עם 16 מיליון צבעים, שליטה דרך אפליקציה, תאימות ל-Alexa ו-Google Home, חיסכון 80% בחשמל.",
    category: "smart-home",
    brand: "Generic",
    imageUrl: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=800&q=80",
    specs: { "חיבור": "E27", "צבעים": "16 מיליון RGB+W", "הספק": "9W", "WiFi": "2.4GHz", "תואם": "Alexa, Google, Smart Life" },
    offers: [
      { vendor: "aliexpress", price: 29, shippingPrice: 0, inStock: true, url: aliLink("smartbulb"), lastUpdated: now },
      { vendor: "amazon", price: 79, shippingPrice: 25, inStock: true, url: amazonLink("B0LMN27282"), lastUpdated: now },
      { vendor: "ksp", price: 129, shippingPrice: 0, inStock: true, url: kspLink("SMARTBULB"), vendorSku: "SMARTBULB", lastUpdated: now },
    ],
    rating: 4.5, reviewCount: 12345, createdAt: now,
  },
  {
    id: "ps5-slim",
    slug: "playstation-5-slim",
    title: "Sony PlayStation 5 Slim Disc",
    description: "קונסולת הדור הבא של סוני - גרסה דקה יותר עם כונן דיסקים, 1TB SSD ובקר DualSense.",
    category: "gaming",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80",
    specs: { "אחסון": "1TB SSD", "כונן": "Ultra HD Blu-ray", "רזולוציה": "עד 8K", "Wi-Fi": "Wi-Fi 6", "כולל": "בקר DualSense" },
    offers: [
      { vendor: "ksp", price: 2390, shippingPrice: 0, inStock: true, url: kspLink("PS5SLIM"), vendorSku: "PS5SLIM", lastUpdated: now },
      { vendor: "amazon", price: 2100, shippingPrice: 250, inStock: false, url: amazonLink("B0CL61F39H"), vendorSku: "B0CL61F39H", lastUpdated: now },
    ],
    rating: 4.9, reviewCount: 15672, createdAt: now,
  },
];

// Auto-fix all URLs in ALL products (MOCK + GENERATED) to use search-based affiliate links
function fixProductLinks(products: Product[]) {
  for (const p of products) {
    const q = p.titleEn || p.title;

    // Fix existing offers
    for (const offer of p.offers) {
      if (offer.vendor === "ksp") offer.url = kspSearch(q);
      else if (offer.vendor === "amazon") offer.url = amazonSearch(q);
      else if (offer.vendor === "aliexpress") offer.url = aliSearch(q);
      else if (offer.vendor === "shein") offer.url = sheinSearch(q);
    }

    // Add SHEIN offer to every product that doesn't have one
    const hasShein = p.offers.some((o) => o.vendor === "shein");
    if (!hasShein) {
      const cheapestPrice = Math.min(
        ...p.offers.filter((o) => o.inStock).map((o) => o.price + o.shippingPrice),
      );
      // Shein is usually 40-60% of cheapest competitor for fashion/beauty
      const sheinEstimate = Math.round(cheapestPrice * 0.55);
      p.offers.push({
        vendor: "shein",
        price: sheinEstimate,
        shippingPrice: 25,
        inStock: true,
        url: sheinSearch(q),
        lastUpdated: "2026-06-09T00:00:00Z",
      });
    }
  }
}

fixProductLinks(MOCK_PRODUCTS);

// Also fix generated products + add Shein to them
fixProductLinks(GENERATED_PRODUCTS);

// Real products (from AliExpress API) + curated mock products (with KSP/Amazon)
const ALL_PRODUCTS: Product[] = [...MOCK_PRODUCTS, ...GENERATED_PRODUCTS];

export function getProductBySlug(slug: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === category);
}

export function getAllProducts(): Product[] {
  return ALL_PRODUCTS;
}
